// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhl25wIK3xZR5FnG3ClAXLa6HAxNUEf6U',
    appId: '1:573391972510:web:73f6e7753cc38858afb38f',
    messagingSenderId: '573391972510',
    projectId: 'ayatunahub-3cdde',
    authDomain: 'ayatunahub-3cdde.firebaseapp.com',
    storageBucket: 'ayatunahub-3cdde.firebasestorage.app',
    measurementId: 'G-RMFC3XFBYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_733mka4MYm97Lp2McsQk0burgjkA1s',
    appId: '1:573391972510:android:a52585969925916cafb38f',
    messagingSenderId: '573391972510',
    projectId: 'ayatunahub-3cdde',
    storageBucket: 'ayatunahub-3cdde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOTQ-xpJDLGCBj50pbWZB0ErnXezwfFv4',
    appId: '1:573391972510:ios:d67f5cec1c2d0d7aafb38f',
    messagingSenderId: '573391972510',
    projectId: 'ayatunahub-3cdde',
    storageBucket: 'ayatunahub-3cdde.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOTQ-xpJDLGCBj50pbWZB0ErnXezwfFv4',
    appId: '1:573391972510:ios:d67f5cec1c2d0d7aafb38f',
    messagingSenderId: '573391972510',
    projectId: 'ayatunahub-3cdde',
    storageBucket: 'ayatunahub-3cdde.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhl25wIK3xZR5FnG3ClAXLa6HAxNUEf6U',
    appId: '1:573391972510:web:1d6710537907dd7eafb38f',
    messagingSenderId: '573391972510',
    projectId: 'ayatunahub-3cdde',
    authDomain: 'ayatunahub-3cdde.firebaseapp.com',
    storageBucket: 'ayatunahub-3cdde.firebasestorage.app',
    measurementId: 'G-M2XNDZSBS0',
  );
}
